### ISSUE TITLE
Can I supress temporary TLS Errors?

### ISSUE THREAD

**Issue by issackelly** [tetratelabs/terraform-provider-checkmate#13]
There are three things I hoped to use this module for, and it passed the first two with flying colors, so thank you!

1. Wait for DNS records to propigate
1. Wait for TLS to be auto-configured on the instance (happens outside terraform, with Caddy and ACME)
1. Wait for my service to be up after starting a new EC2 instance before continuing to provision the service by the API

#1 and #3 work quite well, but I'm getting this error in my logs. It did do the right things, but I'd prefer to supress this as expected noise. 

```
╷
│ Warning: Error connecting to healthcheck endpoint
│ 
│   with module.bowtie-with-aws.checkmate_http_health.baseline_up,
│   on ../terraform-bowtie-with-aws/main.tf line 71, in resource "checkmate_http_health" "baseline_up":
│   71: resource "checkmate_http_health" "baseline_up" {
│ 
│ Get "https://$my_path_here/api/v0/ok": remote error: tls: internal error
╵

```

**Comment by issackelly** [comment]
That's right, though if there's still a TLS error at the end of the `timeout` then I would want to show it as the reason then.

My `golang` chops are quite minimal but I'd be willing to pitch in and be helpful

**Comment by masterfuzz** [comment]
Probably the lines where it does `diag.AddWarning` in the loop should not exist and should just be log messages instead. But the last one probably should still exist. What do you think? Go ahead and make a PR if you want, otherwise I'll get to it eventually

**Comment by masterfuzz** [comment]
Hey @issackelly, v1.6.0 hopefully does what you want, please let me know if not!
